version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: measles_api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0

  client:
    build:
      context: ./client
    container_name: measles_client
    ports:
      - "8000:5000"
    volumes:
      - ./client:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - api
    command: flask run --host=0.0.0.0
